# -*- coding: utf-8 -*-
"""sar_guia_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgJAIeSHCE9wTx940pKcmEMesJ0xRFS_

# 🛰️ Guía de interpretación multisensor — Sentinel-1 · ALOS-2 PALSAR-2 · Sentinel-2
Réplica del formato de la **CEOS Layman's SAR Interpretation Guide v3.0** (Rosenqvist et al., 2023) para tu área de interés.

**Salidas:** panel 3×4 (PNG), cada imagen en PNG, GeoTIFF procesados, reporte PDF científico y `manifiesto.json` con todos los metadatos.

| Fila | Col 1 | Col 2 | Col 3 | Col 4 |
|---|---|---|---|---|
| Sentinel-1 (banda C) | VV | VH | VV/VH | RGB |
| ALOS-2 PALSAR-2 (banda L) | HH | HV | HH/HV | RGB |
| Sentinel-2 (óptico) | NIR | Green | Red | RGB |

### Cómo usarlo
1. `Entorno de ejecución → Ejecutar todas` **o** celda por celda con `Shift + Enter` (recomendado la primera vez).
2. Solo debes editar la **celda 2 (Configuración)**.
3. Las secciones están numeradas igual que los 3 módulos de la app: **Fase 1 Adquisición → Fase 2 Procesamiento → Fase 3 Productos**.
4. Si cambias solo el diseño del panel/PDF, re-ejecuta únicamente la Fase 3 (los datos ya están en memoria y en disco).

## 0 · Instalación (≈1 min)
`earthengine-api`, `geemap` y `pyproj` ya vienen en Colab; se añaden `rasterio` y `reportlab`.
"""

!pip install -q rasterio reportlab asf_search

"""## 1 · Configuración"""

GEE_PROJECT = "wide-origin-466923-d8"

# ---------------- Área de interés (extensión copiada de QGIS, EPSG:3857)
AOI_CRS  = "EPSG:3857"
AOI_BBOX = (-8163798.9687834633514285, 419908.3805525006609969,
            -8158657.8866232894361019, 425023.3658489169902168)
NOMBRE_AOI  = "AOI Meta, Colombia (~5.1 x 5.1 km)"
CRS_TRABAJO = "EPSG:32618"          # UTM 18N

# ---------------- Búsqueda temporal
FECHA_INICIO, FECHA_FIN = "2023-01-01", "2025-12-31"
VENTANA_DIAS        = 15            # separación máxima entre las 3 fechas
S2_NUBES_ESCENA_MAX = 60            # filtro grueso (% de la escena completa)
S2_NUBES_AOI_MAX    = 10            # filtro fino (% dentro del AOI)
MAX_EVAL_NUBES      = 40            # tope de consultas de nubes a GEE

# Para forzar fechas concretas (p.ej. tras explorar en el mapa), descomenta:
FECHAS_MANUALES = None
# FECHAS_MANUALES = {"alos": "2025-02-10", "s1": "2025-02-08", "s2": "2025-02-14"}

# ---------------- Procesamiento
RES        = {"s1": 10, "s2": 10, "alos": 25}   # m de descarga (ALOS nativo 25 m)
LEE_VENTANA, LEE_ENL = 5, 4.4                    # filtro de speckle S1 (ENL IW-GRDH)
K_ALOS_DB  = -83.0                               # calibración JAXA
PERCENTILES_VIS = (2, 98)

# ---------------- Salidas
GUARDAR_EN_DRIVE = True    # True: /content/drive/MyDrive/sar_guia (persiste al cerrar Colab)

"""## 2 · Autenticación, carpetas y utilidades"""

import json, math, requests, warnings
from collections import defaultdict, Counter
from datetime import datetime, timedelta, timezone, date
from pathlib import Path
import numpy as np
import ee, geemap
from pyproj import Transformer
warnings.filterwarnings("ignore", category=RuntimeWarning)

# --- Earth Engine
try:
    ee.Initialize(project=GEE_PROJECT)
except Exception:
    ee.Authenticate()
    ee.Initialize(project=GEE_PROJECT)
print("✅ Earth Engine inicializado")

# --- Carpetas
if GUARDAR_EN_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    BASE = Path("/content/drive/MyDrive/sar_guia")
else:
    BASE = Path("/content/sar_guia")
RAW, PROC, PROD = BASE/"01_raw", BASE/"02_procesado", BASE/"03_productos"
for d in (RAW, PROC, PROD, PROD/"paneles_individuales"):
    d.mkdir(parents=True, exist_ok=True)

# --- Manifiesto: registro único de todo lo que pasa (contrato entre fases)
M = {}
def guardar_manifiesto():
    (BASE/"manifiesto.json").write_text(json.dumps(M, indent=2, ensure_ascii=False, default=str))

# --- AOI: EPSG:3857 -> lon/lat
t = Transformer.from_crs(AOI_CRS, "EPSG:4326", always_xy=True)
x0, y0, x1, y1 = AOI_BBOX
lon, lat = t.transform([x0, x1, x1, x0, x0], [y0, y0, y1, y1, y0])
AOI_LONLAT = [list(p) for p in zip(lon, lat)]
aoi = ee.Geometry.Polygon([AOI_LONLAT], None, False)
M["aoi"] = {"crs_origen": AOI_CRS, "bbox": AOI_BBOX, "lonlat": AOI_LONLAT,
            "crs_trabajo": CRS_TRABAJO, "nombre": NOMBRE_AOI,
            "area_km2": round(aoi.area(1).getInfo() / 1e6, 2)}
print(f"AOI lon {min(lon):.4f}..{max(lon):.4f}  lat {min(lat):.4f}..{max(lat):.4f}  "
      f"área {M['aoi']['area_km2']} km²")
print("Salidas en:", BASE)

# Cell wwlXyqaEeI1M was a duplicate of c06 and has been removed for clarity.

"""---
# FASE 1 · ADQUISICIÓN
### 1.1 Colecciones
| Sensor | Colección GEE | Qué contiene |
|---|---|---|
| Sentinel-1 | `COPERNICUS/S1_GRD_FLOAT` | σ⁰ **lineal**, IW GRDH, ruido térmico removido, calibrado, ortorrectificado |
| ALOS-2 | `JAXA/ALOS/PALSAR-2/Level2_2/ScanSAR` | γ⁰ como DN de amplitud (HH, HV), ángulo local (LIN), máscara (MSK), 25 m, **multi-fecha** |
| Sentinel-2 | `COPERNICUS/S2_SR_HARMONIZED` | Reflectancia de superficie L2A ×10 000 + clasificación SCL |

Es tu mismo código JS, traducido: `print()` → `.getInfo()`, `Map.addLayer` → `geemap`.
"""

COL_S1, COL_S2 = "COPERNICUS/S1_GRD_FLOAT", "COPERNICUS/S2_SR_HARMONIZED"
COL_ALOS, COL_ALOS_ANUAL = "JAXA/ALOS/PALSAR-2/Level2_2/ScanSAR", "JAXA/ALOS/PALSAR/YEARLY/SAR_EPOCH"

col_alos = (ee.ImageCollection(COL_ALOS).filterBounds(aoi)
            .filterDate(FECHA_INICIO, FECHA_FIN)
            .filter(ee.Filter.listContains("system:band_names", "HV")))
col_s1 = (ee.ImageCollection(COL_S1).filterBounds(aoi).filterDate(FECHA_INICIO, FECHA_FIN)
          .filter(ee.Filter.eq("instrumentMode", "IW"))
          .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VV"))
          .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VH")))
col_s2 = (ee.ImageCollection(COL_S2).filterBounds(aoi).filterDate(FECHA_INICIO, FECHA_FIN)
          .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", S2_NUBES_ESCENA_MAX)))

def fechas_por_dia(col, extra=None):
    # {(fecha, extra): [ids]}  -> agrupa slices/tiles del mismo día
    props = ["system:index", "system:time_start"] + ([extra] if extra else [])
    filas = col.reduceColumns(ee.Reducer.toList(len(props)), props).get("list").getInfo()
    g = defaultdict(list)
    for f in filas:
        d = datetime.fromtimestamp(f[1] / 1000, tz=timezone.utc).date()
        g[(d, f[2] if extra else None)].append(f[0])
    return dict(sorted(g.items()))

G_ALOS = fechas_por_dia(col_alos)
G_S1   = fechas_por_dia(col_s1, "relativeOrbitNumber_start")
G_S2   = fechas_por_dia(col_s2)
print(f"ALOS-2 ScanSAR: {len(G_ALOS)} fechas ->", [str(k[0]) for k in G_ALOS])
print(f"Sentinel-1    : {len(G_S1)} fechas (órbitas {sorted({k[1] for k in G_S1})})")
print(f"Sentinel-2    : {len(G_S2)} fechas (< {S2_NUBES_ESCENA_MAX}% nubes en escena)")

"""### 1.2 Exploración visual (tu script JS en Python)
Capas: primera escena ALOS-2, media anual (solo para mirar: **no** usar para medir), y AOI.
"""

def alos_db(img, banda="HH"):
    # gamma0[dB] = 10*log10(DN^2) + K  -> para visualizar en dB
    return img.select(banda).pow(2).log10().multiply(10).add(K_ALOS_DB)

Map = geemap.Map()
Map.centerObject(aoi, 12)
if G_ALOS:
    primera = col_alos.first()
    Map.addLayer(alos_db(primera), {"min": -25, "max": 0}, "ALOS-2 HH dB (primera escena)")
    Map.addLayer(col_alos.select("HH").mean().clip(aoi), {"min": 0, "max": 8000},
                 "ALOS-2 HH media DN (solo visual)", False)
Map.addLayer(ee.Image().paint(aoi, 0, 2), {"palette": "red"}, "Límite AOI")
Map

"""### 1.3 Emparejamiento temporal
ALOS-2 tiene menos fechas → es el **ancla**. Se buscan S1 y S2 tales que `max(fechas) − min(fechas) ≤ VENTANA_DIAS`, se ordenan por cercanía y solo entonces se mide la nubosidad **dentro del AOI** (SCL 3 sombra, 8–9 nube, 10 cirro), para gastar pocas consultas.
"""

_cache_nubes = {}
def nubes_aoi(ids):
    k = tuple(sorted(ids))
    if k not in _cache_nubes:
        scl = ee.ImageCollection([ee.Image(f"{COL_S2}/{i}") for i in ids]).mosaic().select("SCL")
        n = scl.eq(3).Or(scl.eq(8)).Or(scl.eq(9)).Or(scl.eq(10)).rename("n")
        v = n.reduceRegion(ee.Reducer.mean(), aoi, 20, maxPixels=1e9).get("n").getInfo()
        _cache_nubes[k] = 100.0 if v is None else 100 * v
    return _cache_nubes[k]

def fecha_mosaico_anual(anio):
    # Respaldo: mediana de la banda de fecha (días desde lanzamiento ALOS-2, 2014-05-24)
    img = ee.ImageCollection(COL_ALOS_ANUAL).filterDate(f"{anio}-01-01", f"{anio}-12-31").first()
    bandas = img.bandNames().getInfo()
    b = next((x for x in bandas if x.lower() in ("date", "epoch", "obs_date")), None)
    if b is None:
        return date(anio, 7, 1)
    dias = img.select(b).reduceRegion(ee.Reducer.median(), aoi, 25).get(b).getInfo()
    return date(2014, 5, 24) + timedelta(days=int(dias))

def por_fecha(grupos, d):
    # ids de una fecha; en S1 se toma la órbita con más escenas ese día
    cands = [(k, v) for k, v in grupos.items() if k[0] == d]
    if not cands:
        raise ValueError(f"No hay escenas el {d}")
    k, v = max(cands, key=lambda kv: len(kv[1]))
    return k, v

def emparejar():
    if FECHAS_MANUALES:
        fa, f1, f2 = (date.fromisoformat(FECHAS_MANUALES[s]) for s in ("alos", "s1", "s2"))
        _, ia = por_fecha(G_ALOS, fa); k1, i1 = por_fecha(G_S1, f1); _, i2 = por_fecha(G_S2, f2)
        return {"alos": {"fecha": str(fa), "ids": ia, "tipo": "scansar"},
                "s1": {"fecha": str(f1), "ids": i1, "orbita_rel": k1[1]},
                "s2": {"fecha": str(f2), "ids": i2, "nubes_aoi_pct": round(nubes_aoi(i2), 2)},
                "span_dias": (max(fa, f1, f2) - min(fa, f1, f2)).days}

    anclas = [(k[0], v, "scansar") for k, v in G_ALOS.items()]
    if not anclas:
        print("⚠️ Sin ALOS-2 ScanSAR: uso mosaicos anuales (fecha por píxel).")
        for a in range(int(FECHA_INICIO[:4]), int(FECHA_FIN[:4]) + 1):
            try: anclas.append((fecha_mosaico_anual(a), [f"anual_{a}"], "anual"))
            except Exception: pass

    cands = []
    for da, ia, tipo in anclas:
        for (d1, orb), i1 in G_S1.items():
            if abs((d1 - da).days) > VENTANA_DIAS: continue
            for (d2, _), i2 in G_S2.items():
                span = (max(da, d1, d2) - min(da, d1, d2)).days
                if span <= VENTANA_DIAS:
                    cands.append((span, da, ia, tipo, d1, orb, i1, d2, i2))
    cands.sort(key=lambda c: c[0])
    print(f"{len(cands)} combinaciones válidas en tiempo; evaluando nubes…")
    for c in cands[:MAX_EVAL_NUBES]:
        n = nubes_aoi(c[8])
        print(f"  ALOS {c[1]} | S1 {c[4]} | S2 {c[7]} -> nubes AOI {n:5.1f}%")
        if n <= S2_NUBES_AOI_MAX:
            span, da, ia, tipo, d1, orb, i1, d2, i2 = c
            return {"alos": {"fecha": str(da), "ids": ia, "tipo": tipo},
                    "s1": {"fecha": str(d1), "ids": i1, "orbita_rel": orb},
                    "s2": {"fecha": str(d2), "ids": i2, "nubes_aoi_pct": round(n, 2)},
                    "span_dias": span}
    raise RuntimeError("Ninguna combinación cumple. Amplía FECHA_INICIO/FIN, VENTANA_DIAS "
                       "o S2_NUBES_AOI_MAX (celda 1), o usa FECHAS_MANUALES.")

SEL = emparejar()
print("\n✅ Seleccionado:", json.dumps(SEL, indent=1, default=str)[:600])

"""### 1.4 Construcción de imágenes y vista previa de las 3 fechas elegidas"""

def img_s1(ids):
    return ee.ImageCollection([ee.Image(f"{COL_S1}/{i}") for i in ids]).mosaic() \
             .select(["VV", "VH", "angle"]).toFloat()

def img_s2(ids):
    return ee.ImageCollection([ee.Image(f"{COL_S2}/{i}") for i in ids]).mosaic() \
             .select(["B2", "B3", "B4", "B8", "SCL"]).toUint16()

def img_alos(sel):
    if sel["tipo"] == "scansar":
        col = ee.ImageCollection([ee.Image(f"{COL_ALOS}/{i}") for i in sel["ids"]])
    else:
        a = sel["ids"][0].split("_")[1]
        col = ee.ImageCollection(COL_ALOS_ANUAL).filterDate(f"{a}-01-01", f"{a}-12-31")
    return col.mosaic().select(["HH", "HV", "LIN", "MSK"]).toUint16()

IMG = {"s1": img_s1(SEL["s1"]["ids"]), "s2": img_s2(SEL["s2"]["ids"]), "alos": img_alos(SEL["alos"])}

Map2 = geemap.Map()
Map2.centerObject(aoi, 13)
Map2.addLayer(IMG["s2"].clip(aoi), {"bands": ["B4", "B3", "B2"], "min": 0, "max": 2000}, f"S2 RGB {SEL['s2']['fecha']}")
Map2.addLayer(IMG["s1"].select("VV").log10().multiply(10).clip(aoi), {"min": -22, "max": 0}, f"S1 VV dB {SEL['s1']['fecha']}")
Map2.addLayer(alos_db(IMG["alos"]).clip(aoi), {"min": -25, "max": 0}, f"ALOS HH dB {SEL['alos']['fecha']}")
Map2.addLayer(ee.Image().paint(aoi, 0, 2), {"palette": "red"}, "AOI")
Map2

"""### 1.5 Descarga (GeoTIFF con valores físicos sin transformar) y metadatos completos"""

def descargar(img, ruta, escala):
    url = img.getDownloadURL({"region": aoi, "scale": escala, "crs": CRS_TRABAJO, "format": "GEO_TIFF"})
    r = requests.get(url, timeout=600); r.raise_for_status()
    ruta.write_bytes(r.content)
    print(f"  ⬇ {ruta.name}: {len(r.content)/1e6:.2f} MB")

def metadatos(col, ids):
    out = []
    for i in ids:
        if i.startswith("anual_"):
            out.append({"producto": "mosaico anual", "anio": i.split("_")[1]}); continue
        d = ee.Image(f"{col}/{i}").toDictionary().getInfo()
        out.append({k: v for k, v in d.items() if len(str(v)) < 300} | {"id": i})
    return out

INFO = {
 "s1":   ("IW GRDH σ⁰ lineal (GEE: ruido térmico, calibración, ortorrectificación)", ["VV","VH","angle"], COL_S1),
 "s2":   ("L2A reflectancia de superficie (armonizada)", ["B2","B3","B4","B8","SCL"], COL_S2),
 "alos": ("L2.2 ScanSAR γ⁰ (DN de amplitud)" if SEL["alos"]["tipo"] == "scansar"
          else "Mosaico anual γ⁰ (DN de amplitud)", ["HH","HV","LIN","MSK"], COL_ALOS),
}
for s in ("s1", "s2", "alos"):
    ruta = RAW / f"{s}_{SEL[s]['fecha']}.tif"
    descargar(IMG[s], ruta, RES[s])
    prod, bandas, col = INFO[s]
    SEL[s] |= {"archivo": str(ruta), "producto": prod, "bandas": bandas,
               "metadatos": metadatos(col, SEL[s]["ids"])}
M["adquisicion"] = SEL
guardar_manifiesto()
print("✅ Fase 1 completa. Metadatos en manifiesto.json")

"""---
# FASE 2 · PROCESAMIENTO
### Física y matemática aplicada
* **ALOS-2:** γ⁰ = DN² · 10^(K/10), K = −83 dB  ⇔  γ⁰[dB] = 10·log₁₀(DN²) − 83
* **Sentinel-1:** γ⁰ = σ⁰ / cos θ (θ = ángulo elipsoidal; normaliza near/far range, **no** es RTC completa) llevar a RTC la colección OJO
* **Speckle** multiplicativo I = R·n, Var[n] = 1/ENL → filtro de Lee: R̂ = m + k(I − m), k = max(0, 1 − C²ᵤ/C²ᵢ)
* **Regla de oro:** promediar y remuestrear en **potencia lineal**; pasar a dB al final. Cociente co/cross = resta en dB.
* **Sentinel-2:** ρ = DN/10 000; nubes enmascaradas con SCL; NDVI = (NIR − R)/(NIR + R)
"""

import rasterio
from rasterio.warp import reproject, Resampling
from scipy.ndimage import uniform_filter

# ---------- E/S raster
def leer(ruta):
    with rasterio.open(ruta) as ds:
        return ds.read().astype("float64"), ds.profile.copy()

def reproyectar(arr, p_src, p_ref, metodo="bilinear"):
    arr = arr[None] if arr.ndim == 2 else arr
    dst = np.full((arr.shape[0], p_ref["height"], p_ref["width"]), np.nan)
    for b in range(arr.shape[0]):
        reproject(arr[b], dst[b], src_transform=p_src["transform"], src_crs=p_src["crs"],
                  dst_transform=p_ref["transform"], dst_crs=p_ref["crs"],
                  src_nodata=np.nan, dst_nodata=np.nan, resampling=getattr(Resampling, metodo))
    return dst

def escribir(ruta, arr, p_ref, desc, dtype="float32", nodata=np.nan):
    arr = arr[None] if arr.ndim == 2 else arr
    p = p_ref.copy()
    p.update(driver="GTiff", count=arr.shape[0], dtype=dtype, nodata=nodata, compress="deflate")
    with rasterio.open(ruta, "w", **p) as ds:
        ds.write(arr.astype(dtype))
        for i, d in enumerate(desc, 1):
            ds.set_band_description(i, d)

# ---------- Radiometría
def alos_dn_a_lineal(dn):
    out = dn ** 2 * 10 ** (K_ALOS_DB / 10); out[~(dn > 0)] = np.nan; return out
def a_db(lin):   return 10 * np.log10(np.where(lin > 0, lin, np.nan))
def media_db(l): return float(10 * np.log10(np.nanmean(l)))
def std_db(l):   return float(np.nanstd(a_db(l)))

# ---------- Speckle
def lee(img, w=LEE_VENTANA, enl=LEE_ENL):
    mask = ~np.isfinite(img)
    x = np.where(mask, np.nanmedian(img), img)
    m = uniform_filter(x, w)
    var = np.maximum(uniform_filter(x * x, w) - m * m, 0)
    k = np.clip(1 - (1 / enl) / np.maximum(var / np.maximum(m * m, 1e-12), 1e-12), 0, 1)
    out = m + k * (x - m); out[mask] = np.nan
    return out

def enl_estimado(img, w=9):
    x = np.nan_to_num(img); m = uniform_filter(x, w); v = uniform_filter(x * x, w) - m * m
    return float(np.nanmedian((m * m / np.maximum(v, 1e-12))[m > 0]))

# ---------- Color
def estirar(x, p=PERCENTILES_VIS):
    lo, hi = np.nanpercentile(x, p); return np.clip((x - lo) / max(hi - lo, 1e-9), 0, 1)
def rgb_sar(co_db, cx_db):
    return np.dstack([estirar(co_db), estirar(cx_db), estirar(co_db - cx_db)])
def a_uint8(rgb):
    return (np.nan_to_num(rgb) * 254 + 1).astype("uint8").transpose(2, 0, 1)
print("✅ Funciones de procesamiento cargadas")

A = M["adquisicion"]
# ---------- Sentinel-2 = grilla de referencia (10 m)
s2, PERFIL = leer(A["s2"]["archivo"])
b2, b3, b4, b8, scl = s2
nube = np.isin(scl, [3, 8, 9, 10])
REF = {}
for n, b in (("B2", b2), ("B3", b3), ("B4", b4), ("B8", b8)):
    r = b / 10000.0; r[(b == 0) | nube] = np.nan; REF[n] = r
NDVI = (REF["B8"] - REF["B4"]) / (REF["B8"] + REF["B4"])

# ---------- Sentinel-1: sigma0 -> gamma0 -> Lee
s1, p1 = leer(A["s1"]["archivo"])
s1[:, (s1[0] <= 0)] = np.nan
vv, vh, ang = reproyectar(s1, p1, PERFIL, "bilinear")
ENL_VV = enl_estimado(vv)
S1 = {"VV": lee(vv / np.cos(np.deg2rad(ang))), "VH": lee(vh / np.cos(np.deg2rad(ang)))}

# ---------- ALOS-2: DN -> potencia (25 m) -> bilineal a 10 m
al, pa = leer(A["alos"]["archivo"])
pot = np.stack([alos_dn_a_lineal(al[0]), alos_dn_a_lineal(al[1])])
hh, hv = reproyectar(pot, pa, PERFIL, "bilinear")
lin_a, msk_a = reproyectar(al[2:4], pa, PERFIL, "nearest")
AL = {"HH": hh, "HV": hv}

# ---------- Guardar y estadísticas
STATS = {}
for s, g, co, cx in (("s1", S1, "VV", "VH"), ("alos", AL, "HH", "HV")):
    co_db, cx_db = a_db(g[co]), a_db(g[cx])
    escribir(PROC/f"{s}_gamma0_db.tif", np.stack([co_db, cx_db, co_db - cx_db]), PERFIL,
             [f"{co}_dB", f"{cx}_dB", f"{co}-{cx}_dB"])
    escribir(PROC/f"{s}_gamma0_lineal.tif", np.stack([g[co], g[cx]]), PERFIL, [f"{co}_lin", f"{cx}_lin"])
    escribir(PROC/f"{s}_rgb.tif", a_uint8(rgb_sar(co_db, cx_db)), PERFIL, ["R", "G", "B"], "uint8", 0)
    mc, mx = media_db(g[co]), media_db(g[cx])
    STATS[s] = [{"capa": co, "media_db": round(mc, 2), "std_db": round(std_db(g[co]), 2)},
                {"capa": cx, "media_db": round(mx, 2), "std_db": round(std_db(g[cx]), 2)},
                {"capa": f"{co}-{cx}", "media_db": round(mc - mx, 2),     # cociente de medias
                 "std_db": round(float(np.nanstd(co_db - cx_db)), 2)}]

escribir(PROC/"s2_refl.tif", np.stack([REF["B8"], REF["B3"], REF["B4"]]), PERFIL, ["NIR_B8", "Green_B3", "Red_B4"])
escribir(PROC/"s2_ndvi.tif", NDVI, PERFIL, ["NDVI"])
rgb_opt = np.dstack([estirar(REF[b]) ** (1 / 1.2) for b in ("B4", "B3", "B2")])
escribir(PROC/"s2_rgb.tif", a_uint8(rgb_opt), PERFIL, ["R_B4", "G_B3", "B_B2"], "uint8", 0)
f = lambda n, x: {"capa": n, "media": round(float(np.nanmean(x)), 4), "std": round(float(np.nanstd(x)), 4)}
STATS["s2"] = [f("NIR", REF["B8"]), f("Green", REF["B3"]), f("Red", REF["B4"]), f("NDVI", NDVI)]

vals, cnt = np.unique(msk_a[np.isfinite(msk_a)], return_counts=True)
M["procesamiento"] = {"estadisticas": STATS, "extra": {
    "s1": {"angulo_inc_media": float(np.nanmean(ang)), "angulo_inc_min": float(np.nanmin(ang)),
           "angulo_inc_max": float(np.nanmax(ang)), "enl_estimado_VV_crudo": ENL_VV},
    "alos": {"angulo_inc_local_media": float(np.nanmean(np.where(lin_a > 0, lin_a, np.nan))),
             "mascara_valores": {str(int(v)): int(c) for v, c in zip(vals, cnt)}},
    "grilla": {"crs": str(PERFIL["crs"]), "ancho": PERFIL["width"], "alto": PERFIL["height"],
               "pixel_m": abs(PERFIL["transform"][0])}}}
guardar_manifiesto()
for s, v in STATS.items():
    print(s, v)
print("✅ Fase 2 completa. GeoTIFF en", PROC)

"""### 2.x (Opcional) Fase y datos complejos
Los productos GRD y los mosaicos ALOS son **detectados** (|s|² promediado): **la fase se perdió de forma irreversible**. La fase solo existe en productos **SLC** (s = I + jQ).
* Sentinel-1 SLC: libre en ASF (cuenta NASA Earthdata). Su procesamiento requiere **SNAP** (split → órbita → calibración compleja → deburst → subset → C2 → multilook → geocodificación), que es pesado para Colab; se recomienda ejecutarlo en local con el grafo `snap_graphs/s1_slc_c2.xml` del proyecto modular.
* ALOS-2 SLC: **no** es de libre acceso (JAXA).

Abajo: (a) se listan los SLC de S1 disponibles para tu fecha y (b) se valida la matemática de fase con datos sintéticos de correlación conocida.
"""

import asf_search as asf
wkt = "POLYGON((" + ",".join(f"{x} {y}" for x, y in AOI_LONLAT) + "))"
d = date.fromisoformat(M["adquisicion"]["s1"]["fecha"])
res = asf.geo_search(platform=asf.PLATFORM.SENTINEL1, processingLevel=asf.PRODUCT_TYPE.SLC,
                     beamMode=asf.BEAMMODE.IW, intersectsWith=wkt, start=str(d), end=str(d + timedelta(days=1)))
print(f"SLC disponibles el {d}: {len(res)}")
for r in res:
    p = r.properties
    print(" ", p["fileName"], "| órbita", p.get("pathNumber"), "|", p.get("flightDirection"), "|", p.get("url"))

# ---- Matemática de fase y polarimetría dual (Cloude 2007)
def matriz_c2(s_vv, s_vh, w=7):
    c12 = s_vv * np.conj(s_vh)
    return (uniform_filter(np.abs(s_vv)**2, w), uniform_filter(np.abs(s_vh)**2, w),
            uniform_filter(c12.real, w) + 1j * uniform_filter(c12.imag, w))

def h_alpha(c11, c22, c12):
    tr = c11 + c22
    d = np.sqrt(((c11 - c22) / 2)**2 + np.abs(c12)**2)
    lam = np.stack([tr/2 + d, np.maximum(tr/2 - d, 0)])
    a = np.abs(c12) + 1e-20
    alfa_i = np.degrees(np.arccos(np.clip(a / np.sqrt(a**2 + (lam - c11)**2), 0, 1)))
    p = lam / np.maximum(tr, 1e-20)
    H = -np.sum(np.where(p > 0, p * np.log2(np.maximum(p, 1e-20)), 0), axis=0)
    return H, np.sum(p * alfa_i, axis=0)

# Validación: VH correlacionado con VV (ρ=0.6) y desfasado 0.8 rad
rng = np.random.default_rng(0)
cn = lambda: (rng.normal(size=(300, 300)) + 1j * rng.normal(size=(300, 300))) / np.sqrt(2)
a_, b_ = cn(), cn()
s_vv, s_vh = a_, 0.3 * (0.6 * a_ * np.exp(-1j * 0.8) + 0.8 * b_)
c11, c22, c12 = matriz_c2(s_vv, s_vh, 15)
rho = np.abs(c12) / np.sqrt(c11 * c22)
H, alfa = h_alpha(c11, c22, c12)
print(f"ρ={rho.mean():.3f} (real 0.600) | Δφ={np.angle(c12).mean():.3f} rad (real 0.800) | "
      f"H={H.mean():.2f} | α={alfa.mean():.1f}°")

"""---
# FASE 3 · PRODUCTOS
### 3.1 Panel tipo guía CEOS (PNG 300 dpi + PNG individuales)
"""

import matplotlib.pyplot as plt, matplotlib.patheffects as pe
from IPython.display import Image as IImage, display

FILAS = [("s1", "s1_gamma0_db.tif", ["VV", "VH", "VV-VH"], "C-", "s1_rgb.tif", "R: C-VV\nG: C-VH\nB: C-VV-VH"),
         ("alos", "alos_gamma0_db.tif", ["HH", "HV", "HH-HV"], "L-", "alos_rgb.tif", "R: L-HH\nG: L-HV\nB: L-HH-HV"),
         ("s2", "s2_refl.tif", ["NIR", "Green", "Red"], "S2-", "s2_rgb.tif", "R: B4\nG: B3\nB: B2") ]
CONT = [pe.withStroke(linewidth=2.5, foreground="black")]

def rotulo(ax, t):
    ax.text(0.03, 0.97, t, transform=ax.transAxes, color="white", fontsize=10, va="top", path_effects=CONT)

def leyenda(st, s, pref):
    if s == "s2":
        return f"{pref}{st['capa']}: {st['media']:.3f} (\u00b1{st['std']:.3f})"
    return f"{pref}{st['capa']}: {st['media_db']:.1f} (\u00b1{st['std_db']:.1f}) dB"

def barra(ax, pix, ancho, km=1):
    n_pixels = km * 1000 / pix
    bar_len_frac = n_pixels / ancho # Length of the bar in axes fraction

    # Reference point for the box (top-right of the subplot in axes coordinates)
    x_ref_box = 0.98 # Closer to the right edge
    y_ref_box = 0.98 # Closer to the top edge

    # Define dimensions for the box (in axes coordinates)
    # These values are approximate, adjusted for aesthetic spacing
    box_width_frac = bar_len_frac + 0.04
    box_height_frac = 0.08

    # Calculate bottom-left corner of the black background box
    box_x0 = x_ref_box - box_width_frac
    box_y0 = y_ref_box - box_height_frac

    # Add the black rectangle background
    rect = plt.Rectangle((box_x0, box_y0), box_width_frac, box_height_frac,
                         facecolor="black", edgecolor="black", linewidth=0.5,
                         transform=ax.transAxes, zorder=2)
    ax.add_patch(rect)

    # Positions for the text and bar relative to the box (in axes coordinates)
    # Text in the middle-bottom part of the box
    text_x_pos = box_x0 + box_width_frac / 2
    text_y_pos = box_y0 + 0.01 # Small offset from bottom of box

    # Bar just above the text
    bar_x_start = box_x0 + 0.02 # Small padding from left of box
    bar_x_end = bar_x_start + bar_len_frac
    bar_y_pos = box_y0 + box_height_frac - 0.02 # Small offset from top of box

    # Draw the white text
    ax.text(text_x_pos, text_y_pos, f"{km} km", color="white",
            ha="center", va="bottom", fontsize=9, transform=ax.transAxes, zorder=3,
            path_effects=CONT)

    # Draw the white bar
    ax.plot([bar_x_start, bar_x_end], [bar_y_pos, bar_y_pos], color="white", lw=2,
            transform=ax.transAxes, zorder=3)

A, ST = M["adquisicion"], M["procesamiento"]; STATS = ST["estadisticas"]
pix = M["procesamiento"]["extra"]["grilla"]["pixel_m"]
fig, axes = plt.subplots(3, 4, figsize=(17, 14.5), constrained_layout=True)
for fi, (s, arch, et, pref, arch_rgb, trgb) in enumerate(FILAS):
    arr, _ = leer(PROC / arch)
    rgb = leer(PROC / arch_rgb)[0].transpose(1, 2, 0) / 255
    for c in range(3):
        img = estirar(arr[c])
        axes[fi, c].imshow(img, cmap="gray", interpolation="nearest")
        rotulo(axes[fi, c], f"{pref}{et[c]}")
        axes[fi, c].set_xlabel(leyenda(STATS[s][c], s, pref), fontsize=11)
        plt.imsave(PROD/"paneles_individuales"/f"{s}_{et[c].replace('/', '_')}.png", img, cmap="gray")
    axes[fi, 3].imshow(rgb, interpolation="nearest"); rotulo(axes[fi, 3], trgb)
    barra(axes[fi, 3], pix, rgb.shape[1])
    axes[fi, 3].set_xlabel(f"Fecha de observaci\u00f3n: {A[s]['fecha']}", fontsize=11)
    plt.imsave(PROD/"paneles_individuales"/f"{s}_RGB.png", rgb)
    for a in axes[fi]: a.set_xticks([]); a.set_yticks([])
fig.suptitle(f"{NOMBRE_AOI} \u2014 Sentinel-1 (C), ALOS-2 PALSAR-2 (L), Sentinel-2 (\u00f3ptico)\n"
             f"Separaci\u00f3n temporal m\u00e1xima: {A['span_dias']} d\u00edas", fontsize=14, weight="bold")
PANEL = PROD / "panel_guia.png"
fig.savefig(PANEL, dpi=300); plt.close(fig)
display(IImage(str(PANEL), width=1000))

import rasterio
import numpy as np

# Calculate linear differences for Sentinel-1 VV-VH and ALOS-2 HH-HV
# Assuming S1['VV'] and S1['VH'] are already in linear power scale after speckle filter (from c19)
# Assuming AL['HH'] and AL['HV'] are already in linear power scale (from c19)

S1_VV_minus_VH_lin = S1["VV"] - S1["VH"]
ALOS_HH_minus_HV_lin = AL["HH"] - AL["HV"]

# Save these new bands as GeoTIFFs
escribir(PROC/"s1_VV_minus_VH_lin.tif", S1_VV_minus_VH_lin, PERFIL, ["S1_VV_minus_VH_lin"], nodata=np.nan)
escribir(PROC/"alos_HH_minus_HV_lin.tif", ALOS_HH_minus_HV_lin, PERFIL, ["ALOS_HH_minus_HV_lin"], nodata=np.nan)

print("✅ Calculated and saved S1 VV-VH and ALOS HH-HV linear difference bands.")

# Update stats for these new bands, similar to existing STATS structure
def f_lin_diff_stats(n, x):
    return {"capa": n, "media": round(float(np.nanmean(x)), 4), "std": round(float(np.nanstd(x)), 4)}

if "s1_diff" not in STATS:
    STATS["s1_diff"] = []
STATS["s1_diff"].append(f_lin_diff_stats("S1_VV_minus_VH_lin", S1_VV_minus_VH_lin))

if "alos_diff" not in STATS:
    STATS["alos_diff"] = []
STATS["alos_diff"].append(f_lin_diff_stats("ALOS_HH_minus_HV_lin", ALOS_HH_minus_HV_lin))

M["procesamiento"]["estadisticas"] = STATS
guardar_manifiesto()
print("✅ Updated manifest with stats for new difference bands.")

"""### Nuevas bandas de diferencia lineal (VV-HV y HH-HV)

Estas bandas representan la diferencia directa en la potencia lineal (no en dB) entre las polarizaciones co-pol y cross-pol para Sentinel-1 y ALOS-2, respectivamente. Aunque no son productos SAR estándar para la interpretación directa de la retrodispersión como los cocientes en dB, pueden revelar patrones específicos relacionados con la estructura y la orientación de los objetos en la superficie.
"""

import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
from IPython.display import Image as IImage, display

# Reload the new difference bands
S1_VV_minus_VH_lin_img, _ = leer(PROC/"s1_VV_minus_VH_lin.tif")
ALOS_HH_minus_HV_lin_img, _ = leer(PROC/"alos_HH_minus_HV_lin.tif")

fig2, axes2 = plt.subplots(1, 2, figsize=(10, 5), constrained_layout=True)

# Plot S1 VV-VH linear difference
img_s1_diff = estirar(S1_VV_minus_VH_lin_img[0])
axes2[0].imshow(img_s1_diff, cmap="RdBu", interpolation="nearest")
rotulo(axes2[0], "C-VV - C-VH (Lineal)")
axes2[0].set_xlabel(f"Media: {STATS['s1_diff'][0]['media']:.3f} (\u00b1{STATS['s1_diff'][0]['std']:.3f})", fontsize=11)
axes2[0].set_xticks([]); axes2[0].set_yticks([])
plt.imsave(PROD/"paneles_individuales"/"s1_VV_minus_VH_lin.png", img_s1_diff, cmap="RdBu")

# Plot ALOS HH-HV linear difference
img_alos_diff = estirar(ALOS_HH_minus_HV_lin_img[0])
axes2[1].imshow(img_alos_diff, cmap="RdBu", interpolation="nearest")
rotulo(axes2[1], "L-HH - L-HV (Lineal)")
axes2[1].set_xlabel(f"Media: {STATS['alos_diff'][0]['media']:.3f} (\u00b1{STATS['alos_diff'][0]['std']:.3f})", fontsize=11)
axes2[1].set_xticks([]); axes2[1].set_yticks([])
plt.imsave(PROD/"paneles_individuales"/"alos_HH_minus_HV_lin.png", img_alos_diff, cmap="RdBu")

fig2.suptitle("Diferencia Lineal de Bandas SAR", fontsize=14, weight="bold")
plt.show()

"""### 3.1.2 Panel de Comparación Especial: OPERA S1 RTC
En este bloque independiente, realizamos la descarga de los datos corregidos topográficamente por el Jet Propulsion Laboratory (JPL / NASA) correspondientes a la colección `OPERA/RTC/L2_V1/S1` para la fecha elegida, aplicando el filtro adaptativo de Lee y comparándolo directamente.
"""

import ee, requests
from pathlib import Path

# 1. Definir colección y ruta temporal
COL_OPERA_S1 = "OPERA/RTC/L2_V1/S1"
fecha_s1 = SEL["s1"]["fecha"]
ids_s1 = SEL["s1"]["ids"]

# Buscar el ID correspondiente en OPERA para la misma fecha dentro del AOI
opera_col = (ee.ImageCollection(COL_OPERA_S1)
             .filterBounds(aoi)
             .filterDate(fecha_s1, (datetime.strptime(fecha_s1, "%Y-%m-%d") + timedelta(days=1)).strftime("%Y-%m-%d"))
             .filter(ee.Filter.listContains("POLARIZATIONS", "VV"))
             .filter(ee.Filter.listContains("POLARIZATIONS", "VH")))

# Si no encuentra coincidencia exacta en fecha, busca la más cercana dentro de la ventana
if opera_col.size().getInfo() == 0:
    print("⚠️ No se encontró coincidencia exacta en fecha para OPERA. Buscando la más cercana dentro del rango de ventana...")
    opera_col = (ee.ImageCollection(COL_OPERA_S1)
                 .filterBounds(aoi)
                 .filterDate(FECHA_INICIO, FECHA_FIN)
                 .filter(ee.Filter.listContains("POLARIZATIONS", "VV"))
                 .filter(ee.Filter.listContains("POLARIZATIONS", "VH")))
    # Ordenar por cercanía temporal a la fecha de ALOS-2
    da_ee = ee.Date(SEL["alos"]["fecha"])
    def add_dist(img):
        return img.set("dist_days", ee.Number(img.get("system:time_start")).subtract(da_ee.millis()).abs())
    opera_img = ee.Image(opera_col.map(add_dist).sort("dist_days").first())
else:
    opera_img = opera_col.mosaic()

# Clip y selección de bandas VV, VH
img_opera = opera_img.select(["VV", "VH"]).toFloat()
ruta_opera = RAW / f"s1_opera_{fecha_s1}.tif"

# Descarga del GeoTIFF crudo de OPERA
print(f"Iniciando descarga de OPERA S1 RTC para la fecha: {fecha_s1}...")
url_op = img_opera.getDownloadURL({"region": aoi, "scale": RES["s1"], "crs": CRS_TRABAJO, "format": "GEO_TIFF"})
r_op = requests.get(url_op, timeout=600)
r_op.raise_for_status()
ruta_opera.write_bytes(r_op.content)
print(f"✅ Descargado {ruta_opera.name} ({len(r_op.content)/1e6:.2f} MB)")

# 2. Procesamiento radiométrico y filtrado de Speckle (Filtro Lee)
print("Procesando datos de OPERA con filtro de speckle adaptativo (Lee)...")
opera_raw, p_opera = leer(ruta_opera)

# Enmascarar valores nulos
opera_raw[opera_raw <= 0] = np.nan
vv_op = reproyectar(opera_raw[0], p_opera, PERFIL, "bilinear")[0]
vh_op = reproyectar(opera_raw[1], p_opera, PERFIL, "bilinear")[0]

# Aplicar filtro de Lee directamente (ya que OPERA es γ⁰ RTC nativo corregido por relieve)
OPERA_FILTRADO = {
    "VV": lee(vv_op),
    "VH": lee(vh_op)
}

# Guardar outputs de procesamiento en disco
co_op_db = a_db(OPERA_FILTRADO["VV"])
cx_op_db = a_db(OPERA_FILTRADO["VH"])

escribir(PROC/"s1_opera_gamma0_db.tif", np.stack([co_op_db, cx_op_db, co_op_db - cx_op_db]), PERFIL,
         ["VV_dB", "VH_dB", "VV-VH_dB"])
escribir(PROC/"s1_opera_rgb.tif", a_uint8(rgb_sar(co_op_db, cx_op_db)), PERFIL, ["R", "G", "B"], "uint8", 0)

# Calcular estadísticas del área con OPERA
mc_op, mx_op = media_db(OPERA_FILTRADO["VV"]), media_db(OPERA_FILTRADO["VH"])
STATS["s1_opera"] = [
    {"capa": "VV", "media_db": round(mc_op, 2), "std_db": round(std_db(OPERA_FILTRADO["VV"]), 2)},
    {"capa": "VH", "media_db": round(mx_op, 2), "std_db": round(std_db(OPERA_FILTRADO["VH"]), 2)},
    {"capa": "VV-VH", "media_db": round(mc_op - mx_op, 2),
     "std_db": round(float(np.nanstd(co_op_db - cx_op_db)), 2)}
]

M["procesamiento"]["estadisticas"] = STATS
guardar_manifiesto()
print("✅ Procesamiento de OPERA completado y guardado en manifest.json.")

# 3. Graficar el nuevo panel comparativo completo (OPERA RTC + ALOS + S2)
print("Generando el panel guía comparativo especial con OPERA RTC S1...")

FILAS_OPERA = [
    ("s2", "s2_refl.tif", ["NIR", "Green", "Red"], "S2-", "s2_rgb.tif", "R: B4\nG: B3\nB: B2"),
    ("s1_opera", "s1_opera_gamma0_db.tif", ["VV", "VH", "VV-VH"], "C-OPERA-", "s1_opera_rgb.tif", "R: C-VV (RTC)\nG: C-VH (RTC)\nB: C-VV-VH"),
    ("alos", "alos_gamma0_db.tif", ["HH", "HV", "HH-HV"], "L-", "alos_rgb.tif", "R: L-HH\nG: L-HV\nB: L-HH-HV")
]

# Aumentar ligeramente el tamaño de la figura para dar más espacio
fig_op, axes_op = plt.subplots(3, 4, figsize=(18, 15.5), constrained_layout=True)

for fi, (s, arch, et, pref, arch_rgb, trgb) in enumerate(FILAS_OPERA):
    arr, _ = leer(PROC / arch)
    rgb = leer(PROC / arch_rgb)[0].transpose(1, 2, 0) / 255
    for c in range(3):
        img = estirar(arr[c])
        axes_op[fi, c].imshow(img, cmap="gray", interpolation="nearest")
        rotulo(axes_op[fi, c], f"{pref}{et[c]}")
        axes_op[fi, c].set_xlabel(leyenda(STATS[s][c], s, pref), fontsize=11)

    axes_op[fi, 3].imshow(rgb, interpolation="nearest")
    rotulo(axes_op[fi, 3], trgb)
    barra(axes_op[fi, 3], pix, rgb.shape[1]) # Usar la función barra modificada

    fecha_obs = A["s1"]["fecha"] if s == "s1_opera" else A[s]["fecha"]
    axes_op[fi, 3].set_xlabel(f"Fecha de observaci\u00f3n: {fecha_obs}", fontsize=11)
    for a in axes_op[fi]:
        a.set_xticks([])
        a.set_yticks([])

fig_op.suptitle(f"{NOMBRE_AOI} \u2014 OPERA S1 RTC (C), ALOS-2 PALSAR-2 (L), Sentinel-2 (\u00f3ptico)\n"
                f"Separaci\u00f3n temporal m\u00e1xima: {A['span_dias']} d\u00edas", fontsize=14, weight="bold")

# Ajustar el diseño para evitar solapamientos y recortes
fig_op.tight_layout()

PANEL_OPERA = PROD / "panel_guia_opera_rtc.png"
fig_op.savefig(PANEL_OPERA, dpi=300)
plt.close(fig_op)

print(f"\u2705 Panel guardado en {PANEL_OPERA}")
display(IImage(str(PANEL_OPERA), width=1000))

"""### Interpretación de las nuevas bandas y referencia a cultivos

Las diferencias lineales `VV-HV` y `HH-HV` resaltan variaciones en la contribución de la dispersión de volumen y superficie. Una diferencia grande puede indicar una mayor contribución de la polarización co-pol sobre la cross-pol, lo que podría estar relacionado con la orientación de los elementos del terreno o la presencia de estructuras dominantes.

Comparando los valores de nuestro AOI con las referencias de la guía CEOS:

*   **Palma de aceite (Indonesia):** L-HH -7.2 dB, L-HV -14.6 dB, C-VV -5.7 dB, C-VH -13.3 dB. Esto implica diferencias de aproximadamente L-HH/HV ~7.4 dB y C-VV/VH ~7.6 dB. En el caso de **palma de aceite en el borde de un riachuelo** y **pastos cultivados** (probablemente con alguna textura o altura), esperaríamos patrones que reflejen la estructura vertical de las palmas (mayor dispersión de volumen) y la rugosidad de los pastos. La **palma de aceite** se caracteriza por una mayor retrodispersión en HH y VV debido a su estructura de copas y troncos, mientras que los **pastos cultivados** podrían mostrar valores intermedios dependientes de su densidad y altura.

*   **Plantación de caucho (Vietnam):** L-HH -4.8 dB, L-HV -10.6 dB, C-VV -6.5 dB, C-VH -12.8 dB. Aquí, las diferencias son L-HH/HV ~5.8 dB y C-VV/VH ~6.3 dB. La **plantación de caucho** tiende a tener una estructura más uniforme y densa, lo que podría generar patrones de dispersión más homogéneos.

Es importante recordar que estas diferencias lineales (`S1_VV_minus_HV_lin`, `ALOS_HH_minus_HV_lin`) son un indicador diferente a los cocientes en dB. Para una interpretación más robusta, se recomienda analizar conjuntamente estas nuevas bandas con las bandas originales y los cocientes en dB, así como con el NDVI para identificar áreas de vegetación densa.

### 3.2 Reporte PDF científico
"""

import matplotlib
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak

# Fuente con griegos (σ, γ, λ, φ) — viene con matplotlib
fd = Path(matplotlib.get_data_path()) / "fonts" / "ttf"
for n, f_ in (("DV", "DejaVuSans.ttf"), ("DV-B", "DejaVuSans-Bold.ttf"), ("DV-I", "DejaVuSans-Oblique.ttf")):
    pdfmetrics.registerFont(TTFont(n, str(fd / f_)))
registerFontFamily("DV", normal="DV", bold="DV-B", italic="DV-I", boldItalic="DV-B")
AZ = colors.HexColor("#1F4E79"); ss = getSampleStyleSheet()
N  = ParagraphStyle("n", parent=ss["Normal"], fontName="DV", fontSize=9.5, leading=13.5, alignment=4)
H1 = ParagraphStyle("h1", parent=N, fontName="DV-B", fontSize=15, textColor=AZ, spaceBefore=10, spaceAfter=6, alignment=0)
H2 = ParagraphStyle("h2", parent=H1, fontSize=11.5, spaceBefore=8, spaceAfter=3)
T  = ParagraphStyle("t", parent=N, fontSize=7.5, leading=9.5, alignment=0)
TIT = ParagraphStyle("tit", parent=H1, fontSize=22, alignment=1, leading=28)

def tabla(filas, anchos):
    t = Table([[Paragraph(str(c), T) for c in f] for f in filas], colWidths=anchos, repeatRows=1)
    t.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), .3, colors.grey), ("VALIGN", (0, 0), (-1, -1), "TOP"),
                           ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#DCE6F1"))]))
    return t

C_LUZ = 299_792_458.0
REF_CEOS = {  # (L-HH, L-HV, C-VV, C-VH) dB — Rosenqvist et al. 2023, una escena por clase
    "Bosque tropical denso (Colombia)": (-9.4, -13.9, -8.1, -14.6),
    "Deforestación / sucesión secundaria (Colombia)": (-10.9, -18.5, -8.4, -13.1),
    "Bosque inundable (Brasil)": (-2.9, -12.7, -6.5, -12.3),
    "Manglar (Bangladesh)": (-8.7, -15.9, -8.7, -14.9),
    "Plantación de caucho (Vietnam)": (-4.8, -10.6, -6.5, -12.8),
    "Palma de aceite (Indonesia)": (-7.2, -14.6, -5.7, -13.3),
    "Acacia (Indonesia)": (-7.2, -12.3, -9.0, -13.0),
    "Arroz irrigado (Vietnam)": (-12.5, -22.6, -10.3, -16.3),
    "Agricultura de secano (Suiza)": (-11.7, -20.5, -11.3, -17.8),
    "Pastos / potreros (Brasil)": (-14.0, -24.4, -12.0, -19.4),
    "Sabana (Tanzania/Kenia)": (-15.8, -24.9, -10.6, -17.5),
    "Terreno árido rocoso (Kenia)": (-6.9, -15.1, -8.3, -18.4),
    "Agua abierta (Chagos)": (-27.6, -38.9, -16.6, -35.1)}

FUND = [
 ("Naturaleza de la señal", "El SAR es un sensor activo de microondas. Cada píxel SLC es un complejo "
  "<i>s = I + jQ = A·e<super>jφ</super></i>: la amplitud depende de rugosidad, geometría y constante dieléctrica; "
  "la fase codifica la distancia (módulo λ/2) más una fase aleatoria de dispersión. GRD y mosaicos ALOS son "
  "<b>detectados</b> (|s|² promediado), por lo que no contienen fase."),
 ("Longitud de onda y penetración", "λ = c/f. Objetos mucho menores que λ son casi transparentes. Banda L "
  "(λ≈24 cm) atraviesa el dosel e interactúa con ramas y troncos (sensible a biomasa hasta ~100 t/ha); banda C "
  "(λ≈5.5 cm) interactúa con hojas y ramas finas, sensible a vegetación baja, cultivos y rugosidad. El óptico "
  "(0.49–0.83 µm) mide reflectancia solar y no atraviesa nubes."),
 ("Coeficientes de retrodispersión", "σ<super>0</super> = 10·log<sub>10</sub>⟨DN²⟩ + K (amplitud); "
  "γ<super>0</super> = σ<super>0</super>/cos θ. ALOS-2: γ<super>0</super> = 10·log<sub>10</sub>⟨DN²⟩ − 83 dB. "
  "El promedio ⟨·⟩ se calcula en potencia lineal; la desviación estándar en dB, como en la guía CEOS."),
 ("Speckle", "Ruido multiplicativo I = R·n, E[n]=1, Var[n]=1/ENL. Intensidad de un look: exponencial; "
  "amplitud: Rayleigh; fase: uniforme en (−π, π]. Filtro de Lee (k = 1 − C<sub>u</sub>²/C<sub>i</sub>²) en lineal, ENL = 4.4."),
 ("Polarimetría dual y fase", "C2 = ⟨k·k<super>H</super>⟩, k = [s<sub>VV</sub>, s<sub>VH</sub>]<super>T</super>; "
  "coherencia ρ = |C12|/√(C11·C22); Δφ = arg(C12); H = −Σp<sub>i</sub>log<sub>2</sub>p<sub>i</sub>; "
  "α = Σp<sub>i</sub>arccos|e<sub>i1</sub>|. H y α bajos: superficie; H alto: volumen."),
 ("Mecanismos de dispersión", "Directa (co-pol alta: rocas, pendientes, hojas en banda C); especular "
  "(agua calma, suelo liso: oscuro); difusa (superficies rugosas); doble rebote (troncos/tallos sobre agua: "
  "co-pol muy alta, bosque inundado y arroz); volumen (copas: sube la cross-pol)."),
 ("Óptico (Sentinel-2)", "ρ = π·L·d²/(E<sub>sun</sub>·cos θ<sub>s</sub>), corregida atmosféricamente (L2A). "
  "B2 492 nm, B3 560 nm, B4 665 nm, B8 833 nm (10 m). NDVI = (NIR−R)/(NIR+R). Nubes: SCL 3, 8, 9, 10.")]

CLAVES = {"s1": ["id", "platform_number", "instrumentMode", "orbitProperties_pass", "relativeOrbitNumber_start",
                 "resolution_meters", "transmitterReceiverPolarisation", "sliceNumber"],
          "s2": ["id", "SPACECRAFT_NAME", "MGRS_TILE", "PROCESSING_BASELINE", "SENSING_ORBIT_NUMBER",
                 "MEAN_SOLAR_ZENITH_ANGLE", "MEAN_SOLAR_AZIMUTH_ANGLE", "CLOUDY_PIXEL_PERCENTAGE"]}

def pie(c, doc):
    c.saveState(); c.setFont("DV", 7.5); c.setFillColor(colors.grey)
    c.drawString(1.8*cm, 1*cm, "Guía de interpretación multisensor · sar_guia")
    c.drawRightString(A4[0] - 1.8*cm, 1*cm, str(doc.page)); c.restoreState()

A, PR = M["adquisicion"], M["procesamiento"]; ST, EX = PR["estadisticas"], PR["extra"]
PDF = PROD / "guia_interpretacion.pdf"
doc = SimpleDocTemplate(str(PDF), pagesize=A4, leftMargin=1.8*cm, rightMargin=1.8*cm,
                        topMargin=1.6*cm, bottomMargin=1.6*cm, title="Guía de interpretación SAR/óptico")
s = [Spacer(1, 5*cm), Paragraph("Guía de interpretación multisensor", TIT),
     Paragraph("Sentinel-1 (banda C) · ALOS-2 PALSAR-2 (banda L) · Sentinel-2 (óptico)", H2),
     Spacer(1, 1*cm), Paragraph(NOMBRE_AOI, H2),
     Paragraph(f"S1 {A['s1']['fecha']} · ALOS-2 {A['alos']['fecha']} · S2 {A['s2']['fecha']} "
               f"(separación máx. {A['span_dias']} días)", N),
     Paragraph("Metodología basada en Rosenqvist et al. (2023), CEOS Layman's SAR Interpretation Guide v3.0.", N),
     PageBreak()]

g = EX["grilla"]; lo_ = [p[0] for p in AOI_LONLAT]; la_ = [p[1] for p in AOI_LONLAT]
s += [Paragraph("1. Área de interés y grilla de trabajo", H1),
      tabla([["Parámetro", "Valor"],
             ["CRS origen / bbox", f"{AOI_CRS} · {tuple(round(v, 2) for v in AOI_BBOX)}"],
             ["Extensión WGS84", f"lon {min(lo_):.4f}° a {max(lo_):.4f}° · lat {min(la_):.4f}° a {max(la_):.4f}°"],
             ["Área", f"{M['aoi']['area_km2']} km²"], ["CRS de trabajo", g["crs"]],
             ["Grilla común", f"{g['ancho']} × {g['alto']} px · {g['pixel_m']:.1f} m"],
             ["Remuestreo", "S1 y ALOS-2 (25→10 m): bilineal en potencia lineal · S2: referencia"]],
            [5*cm, 12*cm]),
      Paragraph("2. Fundamentos físicos y matemáticos", H1)]
for t_, p_ in FUND:
    s += [Paragraph(t_, H2), Paragraph(p_, N)]
s += [Spacer(1, 6), tabla([["Sensor", "Banda", "Frecuencia", "λ", "Polarización / bandas"],
          ["Sentinel-1 C-SAR", "C", "5.405 GHz", f"{100*C_LUZ/5.405e9:.2f} cm", "VV + VH"],
          ["ALOS-2 PALSAR-2", "L", "1.2365 GHz", f"{100*C_LUZ/1.2365e9:.2f} cm", "HH + HV"],
          ["Sentinel-2 MSI", "Óptico", "—", "492 / 560 / 665 / 833 nm", "B2, B3, B4, B8"]],
          [3.6*cm, 1.6*cm, 2.6*cm, 4.2*cm, 5*cm]),
      Paragraph("λ = c/f. La guía CEOS redondea banda L a ~23.5 cm (PALSAR-1); PALSAR-2 opera a 1.2365 GHz.", T)]

s += [Paragraph("3. Datos y metadatos de las escenas", H1)]
for k, nom in (("s1", "Sentinel-1"), ("alos", "ALOS-2 PALSAR-2"), ("s2", "Sentinel-2")):
    filas = [["Propiedad", "Valor"]]
    for m_ in A[k]["metadatos"]:
        for c_ in (CLAVES.get(k) or list(m_)[:14]):
            if c_ in m_: filas.append([c_, m_[c_]])
    s += [Paragraph(f"{nom} — {A[k]['producto']}", H2),
          Paragraph(f"Fecha {A[k]['fecha']} · escenas: {len(A[k]['ids'])} · bandas: {', '.join(A[k]['bandas'])}", N),
          tabla(filas, [5.5*cm, 11.5*cm])]
s += [Paragraph("Parámetros derivados", H2),
      tabla([["Parámetro", "Valor"],
             ["S1 incidencia elipsoidal media (rango)",
              f"{EX['s1']['angulo_inc_media']:.2f}° ({EX['s1']['angulo_inc_min']:.2f}°–{EX['s1']['angulo_inc_max']:.2f}°)"],
             ["S1 ENL estimado (σ⁰ sin filtrar)", f"{EX['s1']['enl_estimado_VV_crudo']:.2f}"],
             ["ALOS-2 incidencia local media", f"{EX['alos']['angulo_inc_local_media']:.2f}°"],
             ["ALOS-2 máscara (valor: nº píxeles)", EX["alos"]["mascara_valores"]],
             ["S2 nubes en AOI (SCL)", f"{A['s2']['nubes_aoi_pct']} %"]], [7*cm, 10*cm]),
      PageBreak(),
      Paragraph("4. Panel de interpretación", H1),
      Image(str(PANEL), width=17*cm, height=17*cm*14.5/17),
      Paragraph("Bajo cada imagen: media del AOI (calculada en potencia lineal) y desviación estándar (en dB). "
                "Grises estirados al percentil 2–98 de cada canal (no comparables entre sí). RGB SAR: R=co-pol, "
                "G=cross-pol, B=co/cross. RGB óptico: color verdadero.", T), PageBreak()]

v = (ST["alos"][0]["media_db"], ST["alos"][1]["media_db"], ST["s1"][0]["media_db"], ST["s1"][1]["media_db"])
dist = sorted(((k, math.dist(v, r)) for k, r in REF_CEOS.items()), key=lambda x: x[1])[:3]
s += [Paragraph("5. Interpretación", H1),
      Paragraph(f"Medias del AOI: L-HH {v[0]:.1f} dB · L-HV {v[1]:.1f} dB · C-VV {v[2]:.1f} dB · "
                f"C-VH {v[3]:.1f} dB · NDVI {ST['s2'][3]['media']:.2f}.", N),
      Paragraph("Clases de la guía CEOS más cercanas (distancia euclidiana en [L-HH, L-HV, C-VV, C-VH]) — orientativo:", N),
      tabla([["Clase", "L-HH", "L-HV", "C-VV", "C-VH", "Distancia (dB)"]] +
            [[k] + list(REF_CEOS[k]) + [f"{d_:.1f}"] for k, d_ in dist],
            [6*cm, 1.8*cm, 1.8*cm, 1.8*cm, 1.8*cm, 2.8*cm]),
      Paragraph("Claves de lectura", H2),
      Paragraph("• L-HV > −15 dB → volumen en ramas/troncos (bosque o plantación madura); L-HV < −20 dB → "
                "pastos, cultivos, suelo o agua.<br/>• L-HH muy alto con L-HV moderado → doble rebote (bosque "
                "inundado, arroz).<br/>• C-VH responde a vegetación baja y cultivos; C-VV y C-VH bajos → suelo liso "
                "o agua (azul en el RGB).<br/>• NDVI > 0.6 confirma vegetación densa: úsese para validar la lectura SAR.", N),
      Paragraph("6. Precauciones", H1),
      Paragraph("Valores de una sola fecha: dependen de humedad, fenología, viento y lluvia. La banda C se atenúa "
                "con lluvia intensa; en banda L la lluvia puede aumentar HH sobre bosque. El γ⁰ de Sentinel-1 usa el "
                "ángulo elipsoidal (no es RTC completa): en relieve abrupto use productos RTC. Esta edición usa "
                "productos detectados (sin fase); para fase, coherencia y H/α se requiere S1 SLC. La comparación con "
                "la guía CEOS es orientativa, no una clasificación.", N),
      Paragraph("Referencias", H1)]
for r_ in ["Rosenqvist A., Killough B., Dyke G., Borges D. (2023). A Layman's Interpretation Guide to L-band and C-band SAR data, v3.0. CEOS.",
           "Shimada M. (2010). Ortho-rectification and slope correction of SAR data using DEM. IEEE JSTARS 3(4):657–671.",
           "Lee J.-S. (1980). Digital image enhancement and noise filtering by use of local statistics. IEEE TPAMI 2(2).",
           "Cloude S. R. (2007). The dual polarization entropy/alpha decomposition. Proc. PolInSAR, ESA.",
           "Gorelick N. et al. (2017). Google Earth Engine. Remote Sensing of Environment 202:18–27."]:
    s.append(Paragraph(r_, T))
doc.build(s, onFirstPage=pie, onLaterPages=pie)
M["productos"] = {"panel_png": str(PANEL), "pdf": str(PDF),
                  "geotiff": sorted(str(p) for p in PROC.glob("*.tif"))}
guardar_manifiesto()
print("✅ PDF:", PDF)

"""### 3.3 Descargar todo en un ZIP"""

import shutil
from google.colab import files
zipf = shutil.make_archive("/content/sar_guia_resultados", "zip", BASE)
print("ZIP:", zipf)
files.download(zipf)

"""---
## 🧭 Solución de problemas
| Mensaje | Qué hacer |
|---|---|
| `EEException: ... project` | Revisa `GEE_PROJECT` y que la *Earth Engine API* esté habilitada en Google Cloud |
| `ALOS-2 ScanSAR: 0 fechas` | Amplía `FECHA_INICIO/FIN`; el código usará el mosaico anual si no hay ScanSAR |
| `Ninguna combinación cumple` | Sube `VENTANA_DIAS` o `S2_NUBES_AOI_MAX`, o fija `FECHAS_MANUALES` tras mirar los mapas |
| `No hay escenas el …` | La fecha manual no existe: cópiala de las listas impresas en 1.1 |
| Descarga falla por tamaño | AOI demasiado grande: sube los valores de `RES` |
| Colab se reinicia | Con `GUARDAR_EN_DRIVE=True` los archivos persisten; re-ejecuta desde la celda 2 |

**Para retomar el desarrollo en otra conversación**, pega: *"Tengo el notebook `sar_guia_colab.ipynb` (GEE: S1_GRD_FLOAT, ALOS-2 ScanSAR L2.2, S2_SR_HARMONIZED; ventana ±15 d; fases 1-2-3; manifiesto.json) y quiero …"*
"""